#!/usr/bin/env python3
"""Generate the installer's custom-message files.

Inno Setup reads .isl files as UTF-8 only when they carry a byte-order mark,
and expects CRLF line endings. Editors disagree about both, and a mangled .isl
shows up as garbled text in the installer rather than as a build error - so the
files are generated here instead of being hand-maintained.

To add a language: copy the ENGLISH dict, translate the values, add it to
LANGUAGES below, and add one line to the [Languages] section of surl.iss.

Usage:  python scripts/make_translations.py
"""

from __future__ import annotations

import io
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "installer", "windows", "translations")

HEADER = """; SURL custom installer strings - {language}
;
; Generated by scripts/make_translations.py - edit that file, not this one.
;
; These supplement Inno Setup's own message file. Every string SURL adds to the
; wizard lives here, so translating the installer means adding one dict to the
; generator and one line to [Languages] in surl.iss.

[LangOptions]
LanguageName={language_name}
LanguageID=${language_id}

[CustomMessages]
"""

SECTIONS = [
    ("task checkboxes", [
        "TaskGroupIntegration", "TaskGroupShortcuts",
        "TaskAddToPath", "TaskStartMenu", "TaskDesktopIcon",
    ]),
    ("installation source page", [
        "SourcePageCaption", "SourcePageDescription", "SourcePageSubCaption",
        "SourceBundled", "SourceDownload", "DownloadPageDescription",
    ]),
    ("ready page", [
        "ReadyScope", "ReadySource", "ScopeAllUsers", "ScopeCurrentUser",
    ]),
    ("shortcuts", ["ShortcutOpenShell", "ShortcutDocumentation"]),
    ("finish page", ["RunOpenShell", "RunOpenDocs"]),
    ("errors", [
        "ErrorDownloadFailed", "ErrorChecksumMissing",
        "ErrorChecksumMismatch", "ErrorExtractFailed",
    ]),
    ("uninstall", ["UninstallRemoveDataPrompt"]),
]

ENGLISH = {
    "TaskGroupIntegration": "System integration:",
    "TaskGroupShortcuts": "Shortcuts:",
    "TaskAddToPath": "Add SURL to PATH (recommended)",
    "TaskStartMenu": "Create a Start Menu folder",
    "TaskDesktopIcon": "Create a Desktop shortcut",

    "SourcePageCaption": "Installation source",
    "SourcePageDescription":
        "Choose where Setup should take the SURL program files from.",
    "SourcePageSubCaption":
        "Both options install exactly the same program. Downloading verifies the "
        "file against the SHA-256 checksum published with the release.",
    "SourceBundled":
        "Use the files included in this installer (recommended, works offline)",
    "SourceDownload": "Download the verified release from GitHub",
    "DownloadPageDescription":
        "Downloading the SURL release from GitHub and verifying its checksum...",

    "ReadyScope": "Installation scope:",
    "ReadySource": "Program files:",
    "ScopeAllUsers": "All users on this computer",
    "ScopeCurrentUser": "Only for me",

    "ShortcutOpenShell": "SURL Command Prompt",
    "ShortcutDocumentation": "SURL Documentation",

    "RunOpenShell": "Open a command prompt with SURL",
    "RunOpenDocs": "View the documentation",

    "ErrorDownloadFailed":
        "Could not download SURL.%n%nPlease check your internet connection and try "
        "again, or go back and choose the files included in this installer.",
    "ErrorChecksumMissing":
        "Installation aborted.%n%nThe published checksum for this release could not "
        "be read, so the download cannot be verified.",
    "ErrorChecksumMismatch":
        "Installation aborted.%n%nDownloaded file integrity check failed. The file "
        "does not match the SHA-256 checksum published with the release and will "
        "not be installed.",
    "ErrorExtractFailed":
        "Installation aborted.%n%nThe downloaded archive could not be unpacked.",

    "UninstallRemoveDataPrompt":
        "Remove SURL's configuration and cache?%n%nThis deletes the SURL folders in "
        "%APPDATA% and %LOCALAPPDATA%.%n%nWebsites you have downloaded with SURL are "
        "never removed, wherever you saved them.%n%nChoose No to keep your settings.",
}

RUSSIAN = {
    "TaskGroupIntegration": "Интеграция с системой:",
    "TaskGroupShortcuts": "Ярлыки:",
    "TaskAddToPath": "Добавить SURL в PATH (рекомендуется)",
    "TaskStartMenu": "Создать папку в меню «Пуск»",
    "TaskDesktopIcon": "Создать ярлык на рабочем столе",

    "SourcePageCaption": "Источник установки",
    "SourcePageDescription":
        "Выберите, откуда взять файлы программы SURL.",
    "SourcePageSubCaption":
        "Оба варианта устанавливают одну и ту же программу. При загрузке файл "
        "проверяется по контрольной сумме SHA-256, опубликованной вместе с релизом.",
    "SourceBundled":
        "Использовать файлы из этого установщика (рекомендуется, работает без Интернета)",
    "SourceDownload": "Скачать проверенный релиз с GitHub",
    "DownloadPageDescription":
        "Загрузка релиза SURL с GitHub и проверка контрольной суммы...",

    "ReadyScope": "Область установки:",
    "ReadySource": "Файлы программы:",
    "ScopeAllUsers": "Для всех пользователей этого компьютера",
    "ScopeCurrentUser": "Только для меня",

    "ShortcutOpenShell": "Командная строка SURL",
    "ShortcutDocumentation": "Документация SURL",

    "RunOpenShell": "Открыть командную строку с SURL",
    "RunOpenDocs": "Открыть документацию",

    "ErrorDownloadFailed":
        "Не удалось скачать SURL.%n%nПроверьте подключение к Интернету и попробуйте "
        "ещё раз или вернитесь назад и выберите файлы из этого установщика.",
    "ErrorChecksumMissing":
        "Установка прервана.%n%nНе удалось прочитать опубликованную контрольную сумму "
        "релиза, поэтому проверить загрузку невозможно.",
    "ErrorChecksumMismatch":
        "Установка прервана.%n%nПроверка целостности загруженного файла не пройдена. "
        "Файл не совпадает с контрольной суммой SHA-256 из релиза и не будет установлен.",
    "ErrorExtractFailed":
        "Установка прервана.%n%nНе удалось распаковать загруженный архив.",

    "UninstallRemoveDataPrompt":
        "Удалить настройки и кэш SURL?%n%nБудут удалены папки SURL в %APPDATA% и "
        "%LOCALAPPDATA%.%n%nСайты, скачанные с помощью SURL, никогда не удаляются, "
        "где бы вы их ни сохранили.%n%nВыберите «Нет», чтобы сохранить настройки.",
}

# Inno Setup's LanguageName must be written as <hhhh> Unicode escapes so the
# language dialog renders correctly before a codepage is chosen.
def unicode_escape_name(name: str) -> str:
    return "".join("<%04X>" % ord(ch) for ch in name)


LANGUAGES = [
    # (file name, comment language, LanguageName, LanguageID, strings)
    ("surl.en.isl", "English", "English", "0409", ENGLISH),
    ("surl.ru.isl", "Russian", unicode_escape_name("Русский"), "0419", RUSSIAN),
]


def render(language: str, language_name: str, language_id: str,
           strings: "dict[str, str]") -> str:
    missing = set(ENGLISH) - set(strings)
    if missing:
        raise SystemExit(
            "%s is missing translations for: %s" % (language, ", ".join(sorted(missing)))
        )

    out = HEADER.format(
        language=language, language_name=language_name, language_id=language_id
    )
    for title, keys in SECTIONS:
        out += "\n; --- %s %s\n" % (title, "-" * max(3, 60 - len(title)))
        for key in keys:
            out += "%s=%s\n" % (key, strings[key])
    return out


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    for file_name, language, language_name, language_id, strings in LANGUAGES:
        text = render(language, language_name, language_id, strings)
        path = os.path.join(OUT_DIR, file_name)
        # UTF-8 with BOM and CRLF: what Inno Setup requires.
        with io.open(path, "w", encoding="utf-8-sig", newline="\r\n") as handle:
            handle.write(text)
        print("wrote %s (%d bytes)" % (path, os.path.getsize(path)))


if __name__ == "__main__":
    main()
