; SURL custom installer strings - Russian
;
; Generated by scripts/make_translations.py - edit that file, not this one.
;
; These supplement Inno Setup's own message file. Every string SURL adds to the
; wizard lives here, so translating the installer means adding one dict to the
; generator and one line to [Languages] in surl.iss.

[LangOptions]
LanguageName=<0420><0443><0441><0441><043A><0438><0439>
LanguageID=$0419

[CustomMessages]

; --- task checkboxes ---------------------------------------------
TaskGroupIntegration=Интеграция с системой:
TaskGroupShortcuts=Ярлыки:
TaskAddToPath=Добавить SURL в PATH (рекомендуется)
TaskStartMenu=Создать папку в меню «Пуск»
TaskDesktopIcon=Создать ярлык на рабочем столе

; --- installation source page ------------------------------------
SourcePageCaption=Источник установки
SourcePageDescription=Выберите, откуда взять файлы программы SURL.
SourcePageSubCaption=Оба варианта устанавливают одну и ту же программу. При загрузке файл проверяется по контрольной сумме SHA-256, опубликованной вместе с релизом.
SourceBundled=Использовать файлы из этого установщика (рекомендуется, работает без Интернета)
SourceDownload=Скачать проверенный релиз с GitHub
DownloadPageDescription=Загрузка релиза SURL с GitHub и проверка контрольной суммы...

; --- ready page --------------------------------------------------
ReadyScope=Область установки:
ReadySource=Файлы программы:
ScopeAllUsers=Для всех пользователей этого компьютера
ScopeCurrentUser=Только для меня

; --- shortcuts ---------------------------------------------------
ShortcutOpenShell=Командная строка SURL
ShortcutDocumentation=Документация SURL

; --- finish page -------------------------------------------------
RunOpenShell=Открыть командную строку с SURL
RunOpenDocs=Открыть документацию

; --- errors ------------------------------------------------------
ErrorDownloadFailed=Не удалось скачать SURL.%n%nПроверьте подключение к Интернету и попробуйте ещё раз или вернитесь назад и выберите файлы из этого установщика.
ErrorChecksumMissing=Установка прервана.%n%nНе удалось прочитать опубликованную контрольную сумму релиза, поэтому проверить загрузку невозможно.
ErrorChecksumMismatch=Установка прервана.%n%nПроверка целостности загруженного файла не пройдена. Файл не совпадает с контрольной суммой SHA-256 из релиза и не будет установлен.
ErrorExtractFailed=Установка прервана.%n%nНе удалось распаковать загруженный архив.

; --- uninstall ---------------------------------------------------
UninstallRemoveDataPrompt=Удалить настройки и кэш SURL?%n%nБудут удалены папки SURL в %APPDATA% и %LOCALAPPDATA%.%n%nСайты, скачанные с помощью SURL, никогда не удаляются, где бы вы их ни сохранили.%n%nВыберите «Нет», чтобы сохранить настройки.
