; SURL custom installer strings - English
;
; Generated by scripts/make_translations.py - edit that file, not this one.
;
; These supplement Inno Setup's own message file. Every string SURL adds to the
; wizard lives here, so translating the installer means adding one dict to the
; generator and one line to [Languages] in surl.iss.

[LangOptions]
LanguageName=English
LanguageID=$0409

[CustomMessages]

; --- task checkboxes ---------------------------------------------
TaskGroupIntegration=System integration:
TaskGroupShortcuts=Shortcuts:
TaskAddToPath=Add SURL to PATH (recommended)
TaskStartMenu=Create a Start Menu folder
TaskDesktopIcon=Create a Desktop shortcut

; --- installation source page ------------------------------------
SourcePageCaption=Installation source
SourcePageDescription=Choose where Setup should take the SURL program files from.
SourcePageSubCaption=Both options install exactly the same program. Downloading verifies the file against the SHA-256 checksum published with the release.
SourceBundled=Use the files included in this installer (recommended, works offline)
SourceDownload=Download the verified release from GitHub
DownloadPageDescription=Downloading the SURL release from GitHub and verifying its checksum...

; --- ready page --------------------------------------------------
ReadyScope=Installation scope:
ReadySource=Program files:
ScopeAllUsers=All users on this computer
ScopeCurrentUser=Only for me

; --- shortcuts ---------------------------------------------------
ShortcutOpenShell=SURL Command Prompt
ShortcutDocumentation=SURL Documentation

; --- finish page -------------------------------------------------
RunOpenShell=Open a command prompt with SURL
RunOpenDocs=View the documentation

; --- errors ------------------------------------------------------
ErrorDownloadFailed=Could not download SURL.%n%nPlease check your internet connection and try again, or go back and choose the files included in this installer.
ErrorChecksumMissing=Installation aborted.%n%nThe published checksum for this release could not be read, so the download cannot be verified.
ErrorChecksumMismatch=Installation aborted.%n%nDownloaded file integrity check failed. The file does not match the SHA-256 checksum published with the release and will not be installed.
ErrorExtractFailed=Installation aborted.%n%nThe downloaded archive could not be unpacked.

; --- uninstall ---------------------------------------------------
UninstallRemoveDataPrompt=Remove SURL's configuration and cache?%n%nThis deletes the SURL folders in %APPDATA% and %LOCALAPPDATA%.%n%nWebsites you have downloaded with SURL are never removed, wherever you saved them.%n%nChoose No to keep your settings.
